:toc: macro
:toc-title:
:toclevels: 99

# oauth2-implicit

image:https://travis-ci.org/jasonkuhrt/oauth2-implicit.svg?branch=master["Build Status", link="https://travis-ci.org/jasonkuhrt/oauth2-implicit"]

toc::[]




## Installation
```
npm --save install oauth2-implicit
```



## API

### `implicitGrant`

```
implicitGrant :: Options -> Credentials
```

[[implicit-grant-options]]
#### `Options :: {}`

Configure aspects of the Implicit Grant flow.

##### `auth_uri :: String`
The location of the Authorization Service that the Client will run the flow against.

##### `client_id :: String`
The unique identification for this Client. The Authorization Service requires this information from clients trying to run this flow. Every Client who has beforehand registered with the Authorization Service should have this information (it is created during registration time).

##### `scope :: String | Array`
The scope that Client will use in its request to Authorization Server. If `Array` type used scopes will be joined by `+` into a `String`. Authorization servers should accept this format (DoorKeeper ruby does) but please open an issue if you discover otherwise.

##### `state :: String` `optional`
Arbitrary Client data that Authorization Server will pass back to Client in the response phase (redirect to the redirect_uri). For details on state see the link:http://tools.ietf.org/html/rfc6749#section-4.1.1[specification].

##### `redirect_uri :: String` `optional`
The location that Client would like Authorization Service to finish the flow at. The given value must match a URI that was provided to the Authorization Service at registration time.

Defaults to the current protocol plus host (which is what you usually want), examples:

[options="header"]
|===
| Source | Redirect
| `http://foo.bar.io:8000/qux#wux` | `http:/foo.bar.io:8000`
| `https://foo.bar.io?lop=mop` | `https://foo.bar.io`
|===


#### `Credentials :: {}`
<<credentials, `Credentials`>> extracted from the URI hash as put there by the Authorization Server redirection process.



### `requestCredentials`
```
requestCredentials :: Options -> null
```

Make a fresh token request to the authorization server. Note that this function ***does not read the result following redirect***, so your application still needs to use either `implicitGrant()` or `.readCredentials()`. This function is useful if, for example, your app makes some API call to a Resource Server that returns an Authorization Server (AS) error ("invalid token" or "expired token") and you need to make a fresh request to get credentials from said AS.

##### `Options :: {}`
See <<implicit-grant-options, docs for `implicitGrant`>>.



### `readCredentials`
```
readCredentials :: -> Credentials | null
```

Try clear the credentials from the URI Hash and return them as <<credentials, `Credentials`>>. If no credentials are found `null` is returned.


### `parseCredentials`
```
parseCredentials :: String:URIHash -> Credentials
```

Convert String URI Hash credentials into structured <<credentials, `Credentials`>>



## Notes

This library is designed in accordance with Implicit Grant flow as specified in the link:http://tools.ietf.org/html/rfc6749#section-4.2[OAuth2 specification (RFC 6749)].



## Types

### `Credentials`
```yaml
accessToken : String
tokenType   : String
expiresIn   : Number | null
scope       : [String]
state       : String | null
```
